# Lua is not officially supported, but an erlang environment will do.
language: erlang

env:
  global:
    - PACKAGE=sexpr
    - ROCKSPEC=$PACKAGE-git-1.rockspec
    - LUAROCKS_CONFIG=build-aux/luarocks-config.lua
    - LUAROCKS_BASE=luarocks-2.1.2
    - LUAROCKS="$LUA $HOME/bin/luarocks"
  matrix:
    - LUA=lua5.1             LUA_INCDIR=/usr/include/lua5.1     LUA_SUFFIX=5.1
    - LUA=lua5.2             LUA_INCDIR=/usr/include/lua5.2     LUA_SUFFIX=5.2
    - LUA=luajit-2.0.0-beta9 LUA_INCDIR=/usr/include/luajit-2.0 LUA_SUFFIX=5.1

# Tool setup.
install:
  # Put back the links for libyaml, which are missing on recent Travis VMs
  - test -f /usr/lib/libyaml.so ||
    sudo find /usr/lib -name 'libyaml*' -exec ln -s {} /usr/lib \;

  - sudo apt-get install luajit
  - sudo apt-get install libluajit-5.1-dev
  - sudo apt-get install lua5.1
  - sudo apt-get install liblua5.1-dev
  - sudo apt-get install lua5.2
  - sudo apt-get install liblua5.2-dev
  # Install a recent luarocks release locally for everything else.
  - wget http://luarocks.org/releases/$LUAROCKS_BASE.tar.gz
  - tar zxvpf $LUAROCKS_BASE.tar.gz
  - ( cd $LUAROCKS_BASE;
      ./configure
      --prefix=$HOME --lua-version=$LUA_SUFFIX --lua-suffix=$LUA_SUFFIX
      --with-lua-include=$LUA_INCDIR;
      make all install; )

# Configure and build.
script:
  # build luarocks-config.lua
  - make $LUAROCKS_CONFIG
    LUA="$LUA" LUA_INCDIR="$LUA_INCDIR" V=1
    || cat $LUAROCKS_CONFIG

  # Set Lua and Shell paths up for local luarocks tree.
  # this package depends on will be installed.
  - eval `$LUAROCKS path`
  - export PATH=`pwd`/luarocks/bin:$PATH

  # Install extra rocks into $LUAROCKS_CONFIG rocks tree.
  - $LUAROCKS install ldoc; $LUAROCKS install specl;

  # Run self-tests in the `luarocks make` build tree.
  - LUA_PATH=`pwd`'/lib/?.lua;'"${LUA_PATH-;}"
    LUA_CPATH=`pwd`'/ext/?.so;'"${LUA_CPATH-;}"
    LUA_INIT= LUA_INIT_5_2=
    make check V=1
