#! /usr/bin/env lua

-- This software is licensed under the M.I.T. license.
-- The license text is found in "license.txt"

local primitive = require "primitive"
local lisp = require "lisp"

-- The top read-eval loop...
local function REPL ()
  local env = primitive.symbols

  -- Run the prelude
  lisp.evalfile (env, "init.lsp")

  local line
  repeat
    io.write ("> ")
    line = io.read ()
    if line and line ~= ":q" then
      local ok, value = pcall (lisp.evalstring, env, line)
      if ok then
        if value then
          print (tostring (value))
        end
      else
        print ("#error: " .. value)
      end
    end
  until not line or line == ":q"
end

REPL ()

os.exit (0)
